version: '3'

services:
 sources-db:
   container_name: sources_db
   image: postgres:9.6
   environment:
   - POSTGRES_DB=sources
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
   ports:
     - 15436:5432
   volumes:
     - ./tmp/db:/var/lib/postgresql/data

 zookeeper:
   container_name: zookeeper
   image: confluentinc/cp-zookeeper
   environment:
     - ZOOKEEPER_CLIENT_PORT=32181
     - ZOOKEEPER_SERVER_ID=1

 kafka:
   container_name: kafka
   image: confluentinc/cp-kafka
   ports:
     - 29092:29092
   depends_on:
     - zookeeper
   environment:
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_QUEUE_HOST-kafka}:${KAFKA_QUEUE_PORT-29092}
     - KAFKA_BROKER_ID=1
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181

 sources-server:
     container_name: sources_server
     build:
       context: .
       dockerfile: Dockerfile-env
     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
     environment:
       - QUEUE_HOST=${KAFKA_QUEUE_HOST-kafka}
       - QUEUE_PORT=${KAFKA_QUEUE_PORT-29092}
     volumes:
       - .:/opt/sources-api/
     ports:
       - "3000:3000"
     links:
       - sources-db
     depends_on:
       - sources-db

networks:
 default:
   external:
     name: koku_default