#!/bin/bash

function write_encryption_key() {
  echo "== Writing encryption key =="
  cat > $WORKDIR/v2_key << KEY
---
:algorithm: aes-256-cbc
:key: ${ENCRYPTION_KEY}
KEY
}

function check_svc_status() {
  local SVC_NAME=$1 SVC_PORT=$2

  [[ $# -lt 2 ]] && echo "Error something seems wrong, we need at least two parameters to check service status" && exit 1

  echo "== Checking ${SVC_NAME}:$SVC_PORT status =="

  while true; do
    ncat ${SVC_NAME} ${SVC_PORT} < /dev/null && break
    sleep 5
  done
  echo "${SVC_NAME}:${SVC_PORT} - accepting connections"
}

write_encryption_key

# Wait for postgres to be ready
check_svc_status $DATABASE_HOST $DATABASE_PORT

bundle exec rake db:migrate db:seed
bundle exec rails server
