#!/bin/bash

function write_encryption_key() {
  echo "== Writing encryption key =="
  cat > $WORKDIR/v2_key << KEY
---
:algorithm: aes-256-cbc
:key: ${ENCRYPTION_KEY}
KEY
}

function check_svc_status() {
  local SVC_NAME=$1 SVC_PORT=$2

  [[ $# -lt 2 ]] && echo "Error something seems wrong, we need at least two parameters to check service status" && exit 1

  echo "== Checking ${SVC_NAME}:$SVC_PORT status =="

  while true; do
    ncat ${SVC_NAME} ${SVC_PORT} < /dev/null && break
    sleep 5
  done
  echo "${SVC_NAME}:${SVC_PORT} - accepting connections"
}

write_encryption_key

DB_STRING=`ruby<<EOF
require 'json'
file = File.read(ENV['ACG_CONFIG'])
data = JSON.parse(file)
puts data['database']['hostname']
puts data['database']['port']
puts data['database']['username']
puts data['database']['password']
puts data['database']['name']
EOF
`
DB_VALUES=( $DB_STRING )

DATABASE_HOST=${DB_VALUES[0]}
DATABASE_PORT=${DB_VALUES[1]}
DATABASE_USER=${DB_VALUES[2]}
DATABASE_PASSWORD=${DB_VALUES[3]}
DATABASE_NAME=${DB_VALUES[4]}

# Wait for postgres to be ready
check_svc_status $DATABASE_HOST $DATABASE_PORT

bundle exec rake db:migrate && bundle exec rails server -p 8000
